//! This file is auto-generated by zpm-update and *should*
//! not be changed. This file can be checked into your VCS
//! and is able to work standalone.
const std = @import("std");

pub const pkgs = struct {
    pub const libgamestudio = std.build.Pkg{
        .name = "libgamestudio",
        .source = .{ .path = "vendor/libgamestudio/src/main.zig" },
    };
    pub const zlm = std.build.Pkg{
        .name = "zlm",
        .source = .{ .path = "vendor/zlm/zlm.zig" },
    };
    pub const ode = std.build.Pkg{
        .name = "ode",
        .source = .{ .path = "vendor/ode/src/ode.zig" },
    };
};
pub const sdks = struct {
    pub const @"zero-graphics" = @import("vendor/zero-graphics/Sdk.zig");
    pub const ode = @import("vendor/ode/Sdk.zig");
};
